<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Rig-Piling | ACE Contruction Company - New Delhi</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="Guniting | ACE Contruction Company - New Delhi" />
<!-- css -->
<link href="css/bootstrap.min.css" rel="stylesheet" />
<link href="css/cubeportfolio.min.css" rel="stylesheet" />
<link href="css/style.css" rel="stylesheet" />

<!-- for favicon -->

<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
<link rel="icon" href="img/favicon.ico" type="image/x-icon">

<!-- Theme skin -->
<link id="t-colors" href="skins/default.css" rel="stylesheet" />

	<!-- boxed bg -->
	<link id="bodybg" href="bodybg/bg1.css" rel="stylesheet" type="text/css" />

<!-- =======================================================
    Author: SJK Technologies Pvt Ltd
    Author URL: http://sjktechnologies.com
======================================================= -->

</head>
<body>


<div id="wrapper">
	<!-- start header -->
	<?php include('header.php'); ?>
	<!-- end header -->
	<section id="inner-headline">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<ul class="breadcrumb">
					<li><a href="index.php"><i class="fa fa-home"></i></a><i class="icon-angle-right"></i></li>
					<li><a href="#">Services</a><i class="icon-angle-right"></i></li>
					<li class="active">Rigpiling</li>
				</ul>
			</div>
		</div>
	</div>
	</section>
	<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h3>Rig-Piling</h3>

				<img src="img/dummies/rigpiling1.jpg" alt="rigpiling" class="img-responsive" />
	
			
		
				<p>
				A Piling Rig is used to drive piles into soil to provide foundation support for buildings, bridges and other structures. </p>
				<p>
				A heavy weight is placed between guides allowing it to move up and down in a single line..At its optimum height the weight is released which hammers the pile and drives it into the ground.</p>
				

				<h4>Procedure</h4>
				<p>
				Select an appropiate auger piling rig considering local geology,rock strength,its in-situ condition and site access.Ensure pile bore stability using polymer drilling fluid.
				</p>
				<p>
				Clean the pile tip zone by airlift method.Provide geofabric pile liner to ensure pile shaft integrity.
				</p>

				<h4>Advantages</h4>
				<p>
				<ol>	
					More suitable for tension loads at stability elements depending on ability to install cage prior to concrete drying out.
				</ol>
				<ol>Minimal levels of vibration.</ol>
				<ol>Lower noise levels generated by piling rig</ol>
				<ol>Faster installation.</ol>
				</p>
			</div>
		</div>
	</div>
	</section>
<!-- footer section -->
	<?php include('footer.php'); 	?>
	<!-- end of footer section -->
	
</div>
<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
<!-- javascript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="js/jquery.min.js"></script>
<script src="js/modernizr.custom.js"></script>
<script src="js/jquery.easing.1.3.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.appear.js"></script>
<script src="js/stellar.js"></script>
<script src="js/classie.js"></script>
<!-- <script src="js/uisearch.js"></script> -->
<script src="js/jquery.cubeportfolio.min.js"></script>
<script src="js/google-code-prettify/prettify.js"></script>
<script src="js/animate.js"></script>
<script src="js/custom.js"></script>

	
</body>
</html>